/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PowerIndicator {
        "color": string;
        "isLoading": boolean;
    }
}
declare global {
    interface HTMLPowerIndicatorElement extends Components.PowerIndicator, HTMLStencilElement {
    }
    var HTMLPowerIndicatorElement: {
        prototype: HTMLPowerIndicatorElement;
        new (): HTMLPowerIndicatorElement;
    };
    interface HTMLElementTagNameMap {
        "power-indicator": HTMLPowerIndicatorElement;
    }
}
declare namespace LocalJSX {
    interface PowerIndicator {
        "color"?: string;
        "isLoading"?: boolean;
    }
    interface IntrinsicElements {
        "power-indicator": PowerIndicator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "power-indicator": LocalJSX.PowerIndicator & JSXBase.HTMLAttributes<HTMLPowerIndicatorElement>;
        }
    }
}
